// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw-JcJ3tKWnMPTnUosT1SfLj_KiqNkAZI',
    appId: '1:760378827377:android:f93358ed1a0a1575aeb1d0',
    messagingSenderId: '760378827377',
    projectId: 'focusnflow-f2724',
    storageBucket: 'focusnflow-f2724.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjx3ukeylJ2W6GnIhAmzUaZCcPZ5juwk0',
    appId: '1:518881213786:web:822ec676c57a6ca279c763',
    messagingSenderId: '518881213786',
    projectId: 'u28-focusnflow',
    authDomain: 'u28-focusnflow.firebaseapp.com',
    storageBucket: 'u28-focusnflow.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqusGREkNdPgSZ8MYpK7cq4vqHtGMvCqg',
    appId: '1:518881213786:ios:116781875749322879c763',
    messagingSenderId: '518881213786',
    projectId: 'u28-focusnflow',
    storageBucket: 'u28-focusnflow.firebasestorage.app',
    iosBundleId: 'com.example.focusnflow',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqusGREkNdPgSZ8MYpK7cq4vqHtGMvCqg',
    appId: '1:518881213786:ios:116781875749322879c763',
    messagingSenderId: '518881213786',
    projectId: 'u28-focusnflow',
    storageBucket: 'u28-focusnflow.firebasestorage.app',
    iosBundleId: 'com.example.focusnflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjx3ukeylJ2W6GnIhAmzUaZCcPZ5juwk0',
    appId: '1:518881213786:web:8a7c8321d1da38e179c763',
    messagingSenderId: '518881213786',
    projectId: 'u28-focusnflow',
    authDomain: 'u28-focusnflow.firebaseapp.com',
    storageBucket: 'u28-focusnflow.firebasestorage.app',
  );

}